/*
 * IzPack - Copyright 2021 Hitesh A. Bosamiya, All Rights Reserved.
 *
 * http://izpack.org/
 * http://izpack.codehaus.org/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.izforge.izpack.installer.console;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Tests the {@link AbstractTextConsolePanel} class.
 *
 * @author Hitesh A. Bosamiya
 */
public class AbstractTextConsolePanelTest
{
    private AbstractTextConsolePanel abstractTextConsolePanel;

    private static String muchNonsense() {
        StringBuilder buf = new StringBuilder();
        for (int i = 0; i < 33; ++i) {
            // this is generated by MS-Word for nearly each word (here &nbsp;) of the document.
            buf.append("<p class=MsoNormal style='margin-bottom:0cm;line-height:normal'><span");
            buf.append("style='font-size:12.0pt;font-family:\"Courier New\"'>&nbsp;</span></p>");
        }

        return buf.toString();
    }

    @Before
    public void setup()
    {
        abstractTextConsolePanel = new AbstractTextConsolePanel(null)
        {

            @Override
            protected String getText()
            {
                return null;
            }
        };
    }

    @Test
    public void testRemoveHTML()
    {
        String html =
                "<!DOCTYPE html><html class=\"someClass\" >\n" +
                "<head>\n" +
                "    \t<title>  \tWelcome   </title>   \n" +
                "    <style>\n" +
                "        * { font-family: Calibri, Candara, Segoe, \"Segoe UI\", Optima, Arial, sans-serif; }\n" +
                "        h1 { font-size: 20pt; }\n" +
                "        pan.text { font-size: 14pt; }\n" +
                "        span.footer { display: block; font-size: 12pt; }\n" +
                "        body { background-color: #EDEDED; }\n" +
                "    </style>\n" +
                "</head  >\n" +
                "<body>\n" +
                "<table width=\"100%\" cellpadding=10 border=0>\n" +
                "<tr>\n" +
                "<td align=\"right\" valign=\"top\">\n" +
                "<h1>Welcome to IzPack</h1>\n" +
                "</td>\n" +
                "</tr>\n" +
                "</table>\n" +
                muchNonsense() +
                "</body>\n" +
                "</html>\n";
        String expected =  "Welcome\n\nWelcome to IzPack";

        assertEquals(expected, abstractTextConsolePanel.removeHTML(html));
    }

    @Test
    public void testRemoveHTMLWithTitleMissing()
    {
        String html =
                "<!DOCTYPE html><html class=\"someClass\" >\n" +
                        "<body>\n" +
                        "<table width=\"100%\" cellpadding=10 border=0>\n" +
                        "<tr>\n" +
                        "<td align=\"right\" valign=\"top\">\n" +
                        "<h1>Welcome to IzPack</h1>\n" +
                        "</td>\n" +
                        "</tr>\n" +
                        "</table>\n" +
                        muchNonsense() +
                        "</body>\n" +
                        "</html>\n";
        String expected =  "Welcome to IzPack";

        assertEquals(expected, abstractTextConsolePanel.removeHTML(html));
    }

    @Test
    public void testRemoveHTMLForNull()
    {
        assertEquals("", abstractTextConsolePanel.removeHTML(null));
    }

    @Test
    public void testRemoveComplexHTML()
    {
        String html = "<!DOCTYPE html>\n" +
                "<html>\n" +
                "<head>\n" +
                "    <title>README Document</title>\n" +
                "</head>\n" +
                "<body>\n" +
                "<h1>Project README</h1>\n" +
                "\n" +
                "<h2>Introduction</h2>\n" +
                "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget ultricies tincidunt,\n" +
                "    nunc nunc fermentum nisi, eget aliquam nunc nunc nec nunc.</p>\n" +
                "\n" +
                "<h2>Features</h2>\n" +
                "<ul>\n" +
                "    <li>Feature one with <strong>important</strong> details</li>\n" +
                "    <li>Feature two with <em>emphasized</em> information</li>\n" +
                "    <li>Feature three with link example</li>\n" +
                "</ul>\n" +
                "\n" +
                "<h2>Installation</h2>\n" +
                "<ol>\n" +
                "    <li>First step of installation</li>\n" +
                "    <li>Second step of installation</li>\n" +
                "    <li>Third step of installation</li>\n" +
                "</ol>\n" +
                "\n" +
                "<h2>Code Example</h2>\n" +
                "<pre><code>\n" +
                "    function example() {\n" +
                "        console.log(\"This is a code example\");\n" +
                "    }\n" +
                "</code></pre>\n" +
                "\n" +
                "</body>\n" +
                "</html>";

        String expected = "README Document\n" +
            "\n" +
            "Project README\n" +
            "\n" +
            "Introduction\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl\n" +
            "eget ultricies tincidunt, nunc nunc fermentum nisi, eget aliquam nunc nunc nec\n" +
            "nunc.\n" +
            "\n" +
            "Features\n" +
            "- Feature one with important details\n" +
            "- Feature two with emphasized information\n" +
            "- Feature three with link example\n" +
            "\n" +
            "Installation\n" +
            "- First step of installation\n" +
            "- Second step of installation\n" +
            "- Third step of installation\n" +
            "\n" +
            "Code Example\n" +
            "    function example() {\n" +
            "        console.log(\"This is a code example\");\n" +
            "    }";

        assertEquals(expected, abstractTextConsolePanel.removeHTML(html));
    }
}
